import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"></link>
         <link rel="stylesheet" href="assets/css/fontawesome.css"></link>
         <link rel="stylesheet" href="assets/css/templatemo-plot-listing.css"></link>
         <link rel="stylesheet" href="assets/css/animated.css"></link>
         <link rel="stylesheet" href="assets/css/owl.css"></link>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
